class_name CCU02StardustBoost
extends Upgrade
## CCU02 Upgrade : Increase the amount of stardust generated by second.


## Max level.
var max_level : int = 5


##Initialize values.
func _init() -> void:
	level = Game.ref.data.cc_upgrades.u_02_stardust_boost_level
	title = "Stardust Boost"
	base_cost = 1
	cost = 1


## Returns description of the upgrade.
func description() -> String:
	var text : String = "Boost the amount of stardust generated by the Universe Core"
	text += "\n[b]Effect : [/b] +1 stardust / sec."
	if level< max_level:
		text += "\n[b]Cost : [/b] %s Consciousness Core" %cost
	return text


## Returns the current cost based on level and base cost.
func calculate_cost() -> void:
	cost = base_cost


## Returns a boolean whether or not the player can afford buying  the upgrade.
func can_afford() -> bool:
	if level >= max_level:
		return false
	
	if Game.ref.data.consciousness_core >= cost:
		return true
	
	else:
		return false


## Consumes stardust to level up.
func level_up() -> void:
	if level >= max_level:
		return
	
	var error : Error = HandlerConsciousnessCore.ref.consume_consciousness_core(cost)
	
	if error:
		return
	
	level += 1
	Game.ref.data.cc_upgrades.u_02_stardust_boost_level = level
	## Increase level  in Data Resource.
	
	leveled_up.emit()
	HandlerCCUpgrades.ref.upgrade_leveled_up.emit(self)
